name: last-commit
description: extracts last commit depending on event
runs:
  using: "composite"
  steps:
    - name: Setup Environment (PR)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        git fetch ${{ github.event.pull_request.head.sha }}
        echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
    - name: Setup Environment (Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
