name: pr build

on:
  pull_request:
    paths:
      - ".github/workflows/release.yml"
      - "rust-toolchain.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

jobs:
  execute-build:
    uses: ./.github/workflows/build.yml

  persist-metrics:
    name: persist metrics with git-metrics
    runs-on: ubuntu-latest
    needs:
      - execute-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download binaries
        uses: ./.github/actions/download-binaries
      - name: persist metrics
        uses: ./.github/actions/persist-metrics
        with:
          push: "false"

      - name: output git-metrics
        id: diff
        run: |
          echo "metrics<<EOF" >> $GITHUB_OUTPUT
          ./git-metrics_linux-x86_64 diff origin/$GITHUB_BASE_REF..HEAD >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: commenting pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: metrics
          message: |
            🦀 This is how your metrics evolved

            ```
            ${{ steps.diff.outputs.metrics }}
            ```
