name: pr build

on:
  pull_request:
    paths:
      - ".github/workflows/pull-request-build.yml"
      - ".github/workflows/build.yml"
      - "rust-toolchain.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

permissions:
  pull-requests: write

jobs:
  execute-build:
    uses: ./.github/workflows/build.yml

  code-testing:
    uses: ./.github/workflows/code-testing.yml

  persist-metrics:
    name: persist metrics with git-metrics
    runs-on: ubuntu-latest
    needs:
      - execute-build
      - code-testing
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download binaries
        uses: ./.github/actions/download-artifacts
      - name: persist metrics
        uses: ./.github/actions/persist-metrics
        with:
          push: "false"

      - name: execute git check
        uses: jdrouet/action-git-metrics@check
        with:
          binary_path: "./git-metrics_linux-x86_64"
