name: pr build

on:
  pull_request:
    paths:
      - ".github/workflows/pull-request-build.yml"
      - ".github/workflows/build.yml"
      - "rust-toolchain.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

jobs:
  execute-build:
    uses: ./.github/workflows/build.yml

  persist-metrics:
    name: persist metrics with git-metrics
    runs-on: ubuntu-latest
    needs:
      - execute-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download binaries
        uses: ./.github/actions/download-binaries
      - name: persist metrics
        uses: ./.github/actions/persist-metrics
        with:
          push: "false"

      - name: execute git check
        uses: jdrouet/action-check-git-metrics@main
